apiVersion: v1
kind: Template
metadata:
  name: openstack-poc-kafka
  annotations:
    description: kafka pod
    tags: logs,poc,openstack,kafka

parameters:
- name: VOLUME_CAPACITY
  description: Persistent volume capacity per pod
  required: true
  value:  2Gi
- name: OBJECT_NAME_PREFIX
  description: Name prefix for each object created
  required: true
  value: kafka
- name: ZOOKEEPER_SERVICE
  description: DNS name of ZooKeeper service
  required: true
  value: zookeeper
- name: IMAGESTREAM
  description: Imagestream name
  required: true
  value: kafka-openstack-poc

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${OBJECT_NAME_PREFIX}
    template:
      metadata:
        labels:
          deploymentconfig: ${OBJECT_NAME_PREFIX}
      spec:
        containers:
        - name: kafka
          image: ${IMAGESTREAM}
          command:
          - bin/start-kafka.sh
          args:
          - config/server.properties
          - ${ZOOKEEPER_SERVICE}
          - ${OBJECT_NAME_PREFIX}
          - 0
          volumeMounts:
          - mountPath: /tmp/kafka-logs
            name: kafka-logs
          ports:
          - containerPort: 9092
        volumes:
        - name: kafka-logs
          
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - kafka
        from:
          kind: ImageStream
          name: ${IMAGESTREAM}

- apiVersion: v1
  kind: Service
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    ports:
    - port: 9092
    selector:
      deploymentconfig: ${OBJECT_NAME_PREFIX}