apiVersion: v1
kind: Template
metadata:
  name: openstack-poc-zookeeper
  annotations:
    description: Zookeeper pod
    tags: logs,poc,openstack,zookeeper

parameters:
  - name: VOLUME_CAPACITY
    description: Persistent volume capacity per pod
    required: true
    value:  512Mi
  - name: VOLUME_CLAIM_NAME
    description: Persistent claim name
    required: true
    value: app1-pvc
  - name: OBJECT_NAME_PREFIX
    description: Name prefix for each object created
    required: true
    value: kafka-openstack-poc
  - name: IMAGESTREAM
    description: Imagestream name
    required: true
    value: kafka-openstack-poc
  - description: Name of the ImageStreamTag to be used for image.
    displayName: ImageStreamTag
    name: IMAGE_STREAM_TAG
    value: "kafka-openstack-poc:latest"    

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${OBJECT_NAME_PREFIX}
    template:
      metadata:
        labels:
          deploymentconfig: ${OBJECT_NAME_PREFIX}
      spec:
        containers:
        - name: ${OBJECT_NAME_PREFIX}
          image: ${IMAGESTREAM}
          command:
          - bin/zook-start.sh
          args:
          - config/zookeeper.properties
          volumeMounts:
          - mountPath: /tmp/zookeeper
            name: zookeeper
          ports:
          - containerPort: 2181
        volumes:
        - name: zookeeper
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${OBJECT_NAME_PREFIX}
        from:
          kind: ImageStream
          name: ${IMAGESTREAM}

- apiVersion: v1
  kind: Service
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    ports:
    - port: 2181
    selector:
deploymentconfig: ${OBJECT_NAME_PREFIX}
