apiVersion: v1
kind: Template
metadata:
name: openstack-poc-zookeeper
annotations:
  description: Zookeeper pod
  tags: logs,poc,openstack,zookeeper

parameters:
- name: VOLUME_CAPACITY
description: Persistent volume capacity per pod
required: true
value:  512Mi
- name: OBJECT_NAME_PREFIX
description: Name prefix for each object created
required: true
value: openstack-poc-zookp
- name: IMAGESTREAM
description: Imagestream name
required: true
value: kafka-openstack-poc
- description: Name of the ImageStreamTag to be used for image.
displayName: ImageStreamTag
name: IMAGE_STREAM_TAG
value: "kafka-openstack-poc:latest"    

objects:
- apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${OBJECT_NAME_PREFIX}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: ${VOLUME_CAPACITY}

- apiVersion: v1
kind: DeploymentConfig
metadata:
  name: ${OBJECT_NAME_PREFIX}
spec:
  replicas: 1
  selector:
    deploymentconfig: ${OBJECT_NAME_PREFIX}
  template:
    metadata:
      labels:
        deploymentconfig: ${OBJECT_NAME_PREFIX}
    spec:
      containers:
      - name: "zook-service-1"
        image: ${IMAGE_STREAM_TAG}
        env:
        - name: ZOOCFGDIR
          value: '/opt/conf'
        command: ["/opt/zookeeper-3.4.6/entry.sh"]
        volumeMounts:
        - name: data-volume
          mountPath: /opt/zookeeper-data
        - name: config-volume
          mountPath: /opt/conf/
        ports:
        - containerPort: 2181
      volumes:
      - name: data-volume
        configMap:
          name: zk-1-config
        persistentVolumeClaim:
          claimName: ${OBJECT_NAME_PREFIX}  
      - name: config-volume
        configMap:
          name: zk-1-config
        persistentVolumeClaim:
          claimName: ${OBJECT_NAME_PREFIX}
   triggers:
   - type: ConfigChange
   - type: ImageChange
     imageChangeParams:
       automatic: true
       containerNames:
       - "zook-service-1"
       from:
         kkind: ImageStreamTag
         name: ${IMAGE_STREAM_TAG}
       strategy:
    type: Recreate
  paused: false
  revisionHistoryLimit: 2     
