apiVersion: v1
kind: Service
metadata:
  name: zookeeper-intra-service
spec:
  ports:
    - port: 2181
      name: clientport
      targetPort : 2181
      protocol: TCP
  clusterIP: None
  selector:
    name: zookeeper